apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kyir
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kyir
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kyir
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kyir
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kyir
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ayog-tenant/rhtap-demo-app/hacbs-test-project-kyir@sha256:8561479990f33b53ce67f7bb6eda60acff69d9d4d3f1634763167ab3b34f814e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
